---

env:
  node: true
  jest: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

rules:
    no-console: off

extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings
